version: 2

models:
  - name: gold_drivers_by_country
    description: "Table agrégée comptant le nombre de pilotes pour chaque nationalité."

    columns:
      - name: nationalite
        description: "La nationalité (qui sert de clé de regroupement)."
        data_tests:
          - unique
          - not_null

      - name: nombre_de_pilotes
        description: "Le nombre total de pilotes pour cette nationalité."
        data_tests:
          - not_null