version: 2

models:
  - name: silver_drivers
    description: "Table nettoyee contenant les informations des pilotes de Formule 1."

    columns:
      - name: id_pilote
        description: "Identifiant unique du pilote fourni par la source."
        data_tests:
          - unique
          - not_null

      - name: numero_pilote
        description: "Numero permanent du pilote, pouvant etre absent."

      - name: prenom
        description: "Prenom du pilote."
        data_tests:
          - not_null

      - name: nom_pilote
        description: "Nom de famille du pilote, normalise en majuscules."
        data_tests:
          - not_null

      - name: acronyme
        description: "Code court du pilote, pouvant etre absent."

      - name: date_naissance
        description: "Date de naissance du pilote."

      - name: nationalite
        description: "Nationalite du pilote."
        data_tests:
          - not_null