name : Transform F1 Data (dbt)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
      
jobs:
  run-dbt-models:
    runs-on: ubuntu-latest

    env:
          AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
      
      - name: Installer les dependances
        run: pip install -r requirements.txt

      - name: Construire les tables
        run: |
          cd f1_transform
          dbt run --profiles-dir .
      
      - name: Executer tests
        run: |
          cd f1_transform
          dbt test --profiles-dir .
          